// Code generated by esql, DO NOT EDIT.
package sql

import (
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"fmt"
	"github.com/jmoiron/sqlx"

	"github.com/go-kenka/esql/examples/data/migrate"
	"github.com/go-kenka/esql/examples/data/role"
	"github.com/go-kenka/esql/examples/data/user"
)

// Client .
type Client struct {
	DB      *sqlx.DB
	Builder *sql.DialectBuilder
	Schema  *migrate.Schema
	Role    *role.RoleClient
	User    *user.UserClient
}

// NewClient .
func NewClient(db *sqlx.DB) *Client {
	drv := migrate.Driver(db)
	return &Client{
		DB:      db,
		Builder: sql.Dialect(db.DriverName()),
		Schema:  migrate.NewSchema(drv),
		Role:    role.NewRoleClient(db),
		User:    user.NewUserClient(db),
	}
}

// Open .
func Open(driverName, dataSourceName string) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		db, err := sqlx.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(db), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}
