// Code generated by esql, DO NOT EDIT.
package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RoleColumns holds the columns for the "role" table.
	RoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Size: 0, Nullable: false, Unique: true, Increment: true},
		{Name: "role_name", Type: field.TypeString, Size: 20, Nullable: false, Unique: false, Default: ""},
	}
	// RoleTable holds the schema information for the "role" table.
	RoleTable = &schema.Table{
		Name:       "role",
		Columns:    RoleColumns,
		PrimaryKey: []*schema.Column{RoleColumns[0]},
	}

	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Size: 0, Nullable: false, Unique: true, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 255, Nullable: false, Unique: true, Default: "0"},
		{Name: "nike_name", Type: field.TypeString, Size: 255, Nullable: false, Unique: false},
		{Name: "role_id", Type: field.TypeInt, Size: 0, Nullable: false, Unique: false},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}

	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RoleTable,
		UserTable,
	}
)

func init() {
	RoleTable.Annotation = &entsql.Annotation{
		Table: "role",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
