// Code generated by esql, DO NOT EDIT.
package role

import (
	"context"
	"entgo.io/ent/dialect/sql"
	"github.com/jmoiron/sqlx"
)

type RoleDelete struct {
	builder *sql.DeleteBuilder
	db      *sqlx.DB
}

func (d *RoleDelete) Where(p *sql.Predicate) *RoleDelete {
	d.builder.Where(p)
	return d
}

func (d *RoleDelete) Exec(ctx context.Context) (int, error) {
	return d.sqlSave(ctx)
}

func (d *RoleDelete) sqlSave(ctx context.Context) (int, error) {
	query, args := d.builder.Query()
	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	aff, _ := result.RowsAffected()
	return int(aff), nil
}

type RoleDeleteOne struct {
	builder *sql.DeleteBuilder
	db      *sqlx.DB
}

func (d *RoleDeleteOne) Save(ctx context.Context) error {
	return d.sqlSave(ctx)
}

func (d *RoleDeleteOne) sqlSave(ctx context.Context) error {
	query, args := d.builder.Query()
	_, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	return nil
}
